include: package:effective_dart/analysis_options.yaml
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_function_literals_in_foreach_calls: ignore
